<?php


namespace App\models;

use App\core\dbModel;

class blog extends dbModel
{
    public static function gotBlog($table)
    {
        return parent::selectBlog($table); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
        // TODO: Implement rules() method.
    }
}
