<?php


namespace App\models;


use App\core\dbModel;

class blog extends dbModel{

 public function selectBlog($table)
{
    return parent::selectBlog($table); // TODO: Change the autogenerated stub
}



    public function rules(): array
    {
        // TODO: Implement rules() method.
    }
}